name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
      MODEL_URL: ${{ vars.MODEL_URL }}
      TOKENIZER_URL: ${{ vars.TOKENIZER_URL }}
      BUILD_TAG: ${{ vars.BUILD_TAG }}

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-dotnet: 'true'

    - uses: actions/checkout@v3

    - name: Build image
      run: chmod +x ./build.sh && ./build.sh

