name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    env:
      MODEL_URL: ${{ vars.MODEL_URL }}
      TOKENIZER_URL: ${{ vars.TOKENIZER_URL }}
      BUILD_TAG: ${{ vars.BUILD_TAG }}

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-dotnet: 'true'

    - uses: actions/checkout@v3

    - name: Move docker data-root to local pwd
      run: cat /etc/docker/daemon.json && mkdir /home/runner/work/runpod-rwkv/runpod-rwkv/docker && sudo cp daemon.json /etc/docker/daemon.json && sudo systemctl restart docker

    - name: Build image
      run: docker info -f '{{ .DockerRootDir }}' && chmod +x ./build.sh && ./build.sh

