name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download model & tokenizer
      run: chmod +x ./download_model.sh && ./download_model.sh
    - name: Build image
      run: chmod +x ./build.sh && ./build.sh

